service: zoi-rocks-frontend

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1

plugins:
  - serverless-s3-sync

custom:
  bucketName: zoirock-frontend-bucket--${self:provider.stage}
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: dist/
  bucketDeployment:
    blockPublicAccess: true

resources:
  Resources:
    ZoiRockFrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
    S3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: ZoiRockFrontendBucket
        PolicyDocument:
          Statement:
            - Sid: ZoiRockS3CloudFront
              Action: s3:GetObject
              Effect: Allow
              Principal:
                Service: cloudfront.amazonaws.com
              Resource: 'arn:aws:s3:::${self:custom.bucketName}/*'
              
    ZoiRockFrontendOAC:
      Type: AWS::CloudFront::OriginAccessControl
      Properties:
        OriginAccessControlConfig:
          Name: ZoiRockAccessControl--${self:provider.stage}
          OriginAccessControlOriginType: s3
          SigningBehavior: always
          SigningProtocol: sigv4

    ZoiRockCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: ${self:custom.bucketName}.s3.eu-central-1.amazonaws.com
              Id: ZoiRockFrontend
              S3OriginConfig:
                OriginAccessIdentity: ""
              OriginAccessControlId: !GetAtt ZoiRockFrontendOAC.Id
          Enabled: true
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
            - ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            TargetOriginId: ZoiRockFrontend
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            CloudFrontDefaultCertificate: true
